// Generated by scripts/fetch-address-formats.mjs from Shopify's address data.
// Don't edit by hand; run the script again instead.

export const ADDRESS_FORMATS = {
  "Singapore": {
    "code": "SG",
    "phonePrefix": 65,
    "rows": [
      [
        "address1"
      ],
      [
        "address2"
      ],
      [
        "zip"
      ]
    ],
    "labels": {
      "address1": "Address",
      "address2": "Apartment, suite, etc",
      "barangay": null,
      "city": "City",
      "province": "Region",
      "zip": "Postal code"
    },
    "zones": []
  },
  "Malaysia": {
    "code": "MY",
    "phonePrefix": 60,
    "rows": [
      [
        "address1"
      ],
      [
        "address2"
      ],
      [
        "zip",
        "city",
        "province"
      ]
    ],
    "labels": {
      "address1": "Address",
      "address2": "Apartment, suite, etc",
      "barangay": null,
      "city": "City",
      "province": "State/territory",
      "zip": "Postcode"
    },
    "zones": [
      {
        "name": "Johor",
        "code": "JHR"
      },
      {
        "name": "Kedah",
        "code": "KDH"
      },
      {
        "name": "Kelantan",
        "code": "KTN"
      },
      {
        "name": "Kuala Lumpur",
        "code": "KUL"
      },
      {
        "name": "Labuan",
        "code": "LBN"
      },
      {
        "name": "Malacca",
        "code": "MLK"
      },
      {
        "name": "Negeri Sembilan",
        "code": "NSN"
      },
      {
        "name": "Pahang",
        "code": "PHG"
      },
      {
        "name": "Penang",
        "code": "PNG"
      },
      {
        "name": "Perak",
        "code": "PRK"
      },
      {
        "name": "Perlis",
        "code": "PLS"
      },
      {
        "name": "Putrajaya",
        "code": "PJY"
      },
      {
        "name": "Sabah",
        "code": "SBH"
      },
      {
        "name": "Sarawak",
        "code": "SWK"
      },
      {
        "name": "Selangor",
        "code": "SGR"
      },
      {
        "name": "Terengganu",
        "code": "TRG"
      }
    ]
  },
  "Hong Kong": {
    "code": "HK",
    "phonePrefix": 852,
    "rows": [
      [
        "address1"
      ],
      [
        "address2"
      ],
      [
        "city",
        "province"
      ]
    ],
    "labels": {
      "address1": "Address",
      "address2": "Apartment, suite, etc",
      "barangay": null,
      "city": "District",
      "province": "Region",
      "zip": "Postal code"
    },
    "zones": [
      {
        "name": "Hong Kong Island",
        "code": "HK"
      },
      {
        "name": "Kowloon",
        "code": "KL"
      },
      {
        "name": "New Territories",
        "code": "NT"
      }
    ]
  },
  "Philippines": {
    "code": "PH",
    "phonePrefix": 63,
    "rows": [
      [
        "address1"
      ],
      [
        "address2",
        "barangay"
      ],
      [
        "zip",
        "city"
      ],
      [
        "province"
      ]
    ],
    "labels": {
      "address1": "Address",
      "address2": "Apartment, suite, etc.",
      "barangay": "Barangay",
      "city": "City",
      "province": "Region",
      "zip": "Postal code"
    },
    "zones": [
      {
        "name": "Abra",
        "code": "PH-ABR"
      },
      {
        "name": "Agusan del Norte",
        "code": "PH-AGN"
      },
      {
        "name": "Agusan del Sur",
        "code": "PH-AGS"
      },
      {
        "name": "Aklan",
        "code": "PH-AKL"
      },
      {
        "name": "Albay",
        "code": "PH-ALB"
      },
      {
        "name": "Antique",
        "code": "PH-ANT"
      },
      {
        "name": "Apayao",
        "code": "PH-APA"
      },
      {
        "name": "Aurora",
        "code": "PH-AUR"
      },
      {
        "name": "Basilan",
        "code": "PH-BAS"
      },
      {
        "name": "Bataan",
        "code": "PH-BAN"
      },
      {
        "name": "Batanes",
        "code": "PH-BTN"
      },
      {
        "name": "Batangas",
        "code": "PH-BTG"
      },
      {
        "name": "Benguet",
        "code": "PH-BEN"
      },
      {
        "name": "Biliran",
        "code": "PH-BIL"
      },
      {
        "name": "Bohol",
        "code": "PH-BOH"
      },
      {
        "name": "Bukidnon",
        "code": "PH-BUK"
      },
      {
        "name": "Bulacan",
        "code": "PH-BUL"
      },
      {
        "name": "Cagayan",
        "code": "PH-CAG"
      },
      {
        "name": "Camarines Norte",
        "code": "PH-CAN"
      },
      {
        "name": "Camarines Sur",
        "code": "PH-CAS"
      },
      {
        "name": "Camiguin",
        "code": "PH-CAM"
      },
      {
        "name": "Capiz",
        "code": "PH-CAP"
      },
      {
        "name": "Catanduanes",
        "code": "PH-CAT"
      },
      {
        "name": "Cavite",
        "code": "PH-CAV"
      },
      {
        "name": "Cebu",
        "code": "PH-CEB"
      },
      {
        "name": "Cotabato",
        "code": "PH-NCO"
      },
      {
        "name": "Davao Occidental",
        "code": "PH-DVO"
      },
      {
        "name": "Davao Oriental",
        "code": "PH-DAO"
      },
      {
        "name": "Compostela Valley",
        "code": "PH-COM"
      },
      {
        "name": "Davao del Norte",
        "code": "PH-DAV"
      },
      {
        "name": "Davao del Sur",
        "code": "PH-DAS"
      },
      {
        "name": "Dinagat Islands",
        "code": "PH-DIN"
      },
      {
        "name": "Eastern Samar",
        "code": "PH-EAS"
      },
      {
        "name": "Guimaras",
        "code": "PH-GUI"
      },
      {
        "name": "Ifugao",
        "code": "PH-IFU"
      },
      {
        "name": "Ilocos Norte",
        "code": "PH-ILN"
      },
      {
        "name": "Ilocos Sur",
        "code": "PH-ILS"
      },
      {
        "name": "Iloilo",
        "code": "PH-ILI"
      },
      {
        "name": "Isabela",
        "code": "PH-ISA"
      },
      {
        "name": "Kalinga",
        "code": "PH-KAL"
      },
      {
        "name": "La Union",
        "code": "PH-LUN"
      },
      {
        "name": "Laguna",
        "code": "PH-LAG"
      },
      {
        "name": "Lanao del Norte",
        "code": "PH-LAN"
      },
      {
        "name": "Lanao del Sur",
        "code": "PH-LAS"
      },
      {
        "name": "Leyte",
        "code": "PH-LEY"
      },
      {
        "name": "Maguindanao",
        "code": "PH-MAG"
      },
      {
        "name": "Marinduque",
        "code": "PH-MAD"
      },
      {
        "name": "Masbate",
        "code": "PH-MAS"
      },
      {
        "name": "Metro Manila",
        "code": "PH-00"
      },
      {
        "name": "Misamis Occidental",
        "code": "PH-MSC"
      },
      {
        "name": "Misamis Oriental",
        "code": "PH-MSR"
      },
      {
        "name": "Mountain",
        "code": "PH-MOU"
      },
      {
        "name": "Negros Occidental",
        "code": "PH-NEC"
      },
      {
        "name": "Negros Oriental",
        "code": "PH-NER"
      },
      {
        "name": "Northern Samar",
        "code": "PH-NSA"
      },
      {
        "name": "Nueva Ecija",
        "code": "PH-NUE"
      },
      {
        "name": "Nueva Vizcaya",
        "code": "PH-NUV"
      },
      {
        "name": "Occidental Mindoro",
        "code": "PH-MDC"
      },
      {
        "name": "Oriental Mindoro",
        "code": "PH-MDR"
      },
      {
        "name": "Palawan",
        "code": "PH-PLW"
      },
      {
        "name": "Pampanga",
        "code": "PH-PAM"
      },
      {
        "name": "Pangasinan",
        "code": "PH-PAN"
      },
      {
        "name": "Quezon",
        "code": "PH-QUE"
      },
      {
        "name": "Quirino",
        "code": "PH-QUI"
      },
      {
        "name": "Rizal",
        "code": "PH-RIZ"
      },
      {
        "name": "Romblon",
        "code": "PH-ROM"
      },
      {
        "name": "Samar",
        "code": "PH-WSA"
      },
      {
        "name": "Sarangani",
        "code": "PH-SAR"
      },
      {
        "name": "Siquijor",
        "code": "PH-SIG"
      },
      {
        "name": "Sorsogon",
        "code": "PH-SOR"
      },
      {
        "name": "South Cotabato",
        "code": "PH-SCO"
      },
      {
        "name": "Southern Leyte",
        "code": "PH-SLE"
      },
      {
        "name": "Sultan Kudarat",
        "code": "PH-SUK"
      },
      {
        "name": "Sulu",
        "code": "PH-SLU"
      },
      {
        "name": "Surigao del Norte",
        "code": "PH-SUN"
      },
      {
        "name": "Surigao del Sur",
        "code": "PH-SUR"
      },
      {
        "name": "Tarlac",
        "code": "PH-TAR"
      },
      {
        "name": "Tawi-Tawi",
        "code": "PH-TAW"
      },
      {
        "name": "Zambales",
        "code": "PH-ZMB"
      },
      {
        "name": "Zamboanga Sibugay",
        "code": "PH-ZSI"
      },
      {
        "name": "Zamboanga del Norte",
        "code": "PH-ZAN"
      },
      {
        "name": "Zamboanga del Sur",
        "code": "PH-ZAS"
      }
    ]
  },
  "Thailand": {
    "code": "TH",
    "phonePrefix": 66,
    "rows": [
      [
        "address1"
      ],
      [
        "address2"
      ],
      [
        "city",
        "province",
        "zip"
      ]
    ],
    "labels": {
      "address1": "Address",
      "address2": "Apartment, suite, etc",
      "barangay": null,
      "city": "City",
      "province": "Province",
      "zip": "Postal code"
    },
    "zones": [
      {
        "name": "Amnat Charoen",
        "code": "TH-37"
      },
      {
        "name": "Ang Thong",
        "code": "TH-15"
      },
      {
        "name": "Bangkok",
        "code": "TH-10"
      },
      {
        "name": "Bueng Kan",
        "code": "TH-38"
      },
      {
        "name": "Buri Ram",
        "code": "TH-31"
      },
      {
        "name": "Chachoengsao",
        "code": "TH-24"
      },
      {
        "name": "Chai Nat",
        "code": "TH-18"
      },
      {
        "name": "Chaiyaphum",
        "code": "TH-36"
      },
      {
        "name": "Chanthaburi",
        "code": "TH-22"
      },
      {
        "name": "Chiang Mai",
        "code": "TH-50"
      },
      {
        "name": "Chiang Rai",
        "code": "TH-57"
      },
      {
        "name": "Chon Buri",
        "code": "TH-20"
      },
      {
        "name": "Chumphon",
        "code": "TH-86"
      },
      {
        "name": "Kalasin",
        "code": "TH-46"
      },
      {
        "name": "Kamphaeng Phet",
        "code": "TH-62"
      },
      {
        "name": "Kanchanaburi",
        "code": "TH-71"
      },
      {
        "name": "Khon Kaen",
        "code": "TH-40"
      },
      {
        "name": "Krabi",
        "code": "TH-81"
      },
      {
        "name": "Lampang",
        "code": "TH-52"
      },
      {
        "name": "Lamphun",
        "code": "TH-51"
      },
      {
        "name": "Loei",
        "code": "TH-42"
      },
      {
        "name": "Lopburi",
        "code": "TH-16"
      },
      {
        "name": "Mae Hong Son",
        "code": "TH-58"
      },
      {
        "name": "Maha Sarakham",
        "code": "TH-44"
      },
      {
        "name": "Mukdahan",
        "code": "TH-49"
      },
      {
        "name": "Nakhon Nayok",
        "code": "TH-26"
      },
      {
        "name": "Nakhon Pathom",
        "code": "TH-73"
      },
      {
        "name": "Nakhon Phanom",
        "code": "TH-48"
      },
      {
        "name": "Nakhon Ratchasima",
        "code": "TH-30"
      },
      {
        "name": "Nakhon Sawan",
        "code": "TH-60"
      },
      {
        "name": "Nakhon Si Thammarat",
        "code": "TH-80"
      },
      {
        "name": "Nan",
        "code": "TH-55"
      },
      {
        "name": "Narathiwat",
        "code": "TH-96"
      },
      {
        "name": "Nong Bua Lam Phu",
        "code": "TH-39"
      },
      {
        "name": "Nong Khai",
        "code": "TH-43"
      },
      {
        "name": "Nonthaburi",
        "code": "TH-12"
      },
      {
        "name": "Pathum Thani",
        "code": "TH-13"
      },
      {
        "name": "Pattani",
        "code": "TH-94"
      },
      {
        "name": "Pattaya",
        "code": "TH-S"
      },
      {
        "name": "Phang Nga",
        "code": "TH-82"
      },
      {
        "name": "Phatthalung",
        "code": "TH-93"
      },
      {
        "name": "Phayao",
        "code": "TH-56"
      },
      {
        "name": "Phetchabun",
        "code": "TH-67"
      },
      {
        "name": "Phetchaburi",
        "code": "TH-76"
      },
      {
        "name": "Phichit",
        "code": "TH-66"
      },
      {
        "name": "Phitsanulok",
        "code": "TH-65"
      },
      {
        "name": "Phra Nakhon Si Ayutthaya",
        "code": "TH-14"
      },
      {
        "name": "Phrae",
        "code": "TH-54"
      },
      {
        "name": "Phuket",
        "code": "TH-83"
      },
      {
        "name": "Prachin Buri",
        "code": "TH-25"
      },
      {
        "name": "Prachuap Khiri Khan",
        "code": "TH-77"
      },
      {
        "name": "Ranong",
        "code": "TH-85"
      },
      {
        "name": "Ratchaburi",
        "code": "TH-70"
      },
      {
        "name": "Rayong",
        "code": "TH-21"
      },
      {
        "name": "Roi Et",
        "code": "TH-45"
      },
      {
        "name": "Sa Kaeo",
        "code": "TH-27"
      },
      {
        "name": "Sakon Nakhon",
        "code": "TH-47"
      },
      {
        "name": "Samut Prakan",
        "code": "TH-11"
      },
      {
        "name": "Samut Sakhon",
        "code": "TH-74"
      },
      {
        "name": "Samut Songkhram",
        "code": "TH-75"
      },
      {
        "name": "Saraburi",
        "code": "TH-19"
      },
      {
        "name": "Satun",
        "code": "TH-91"
      },
      {
        "name": "Sing Buri",
        "code": "TH-17"
      },
      {
        "name": "Si Sa Ket",
        "code": "TH-33"
      },
      {
        "name": "Songkhla",
        "code": "TH-90"
      },
      {
        "name": "Sukhothai",
        "code": "TH-64"
      },
      {
        "name": "Suphanburi",
        "code": "TH-72"
      },
      {
        "name": "Surat Thani",
        "code": "TH-84"
      },
      {
        "name": "Surin",
        "code": "TH-32"
      },
      {
        "name": "Tak",
        "code": "TH-63"
      },
      {
        "name": "Trang",
        "code": "TH-92"
      },
      {
        "name": "Trat",
        "code": "TH-23"
      },
      {
        "name": "Ubon Ratchathani",
        "code": "TH-34"
      },
      {
        "name": "Udon Thani",
        "code": "TH-41"
      },
      {
        "name": "Uthai Thani",
        "code": "TH-61"
      },
      {
        "name": "Uttaradit",
        "code": "TH-53"
      },
      {
        "name": "Yala",
        "code": "TH-95"
      },
      {
        "name": "Yasothon",
        "code": "TH-35"
      }
    ]
  },
  "Indonesia": {
    "code": "ID",
    "phonePrefix": 62,
    "rows": [
      [
        "address1"
      ],
      [
        "address2"
      ],
      [
        "city"
      ],
      [
        "province",
        "zip"
      ]
    ],
    "labels": {
      "address1": "Address",
      "address2": "Apartment, suite, etc",
      "barangay": null,
      "city": "City",
      "province": "Province",
      "zip": "Postal code"
    },
    "zones": [
      {
        "name": "Aceh",
        "code": "AC"
      },
      {
        "name": "Bali",
        "code": "BA"
      },
      {
        "name": "Bangka–Belitung Islands",
        "code": "BB"
      },
      {
        "name": "Banten",
        "code": "BT"
      },
      {
        "name": "Bengkulu",
        "code": "BE"
      },
      {
        "name": "Gorontalo",
        "code": "GO"
      },
      {
        "name": "Jakarta",
        "code": "JK"
      },
      {
        "name": "Jambi",
        "code": "JA"
      },
      {
        "name": "West Java",
        "code": "JB"
      },
      {
        "name": "Central Java",
        "code": "JT"
      },
      {
        "name": "East Java",
        "code": "JI"
      },
      {
        "name": "West Kalimantan",
        "code": "KB"
      },
      {
        "name": "South Kalimantan",
        "code": "KS"
      },
      {
        "name": "Central Kalimantan",
        "code": "KT"
      },
      {
        "name": "East Kalimantan",
        "code": "KI"
      },
      {
        "name": "North Kalimantan",
        "code": "KU"
      },
      {
        "name": "Riau Islands",
        "code": "KR"
      },
      {
        "name": "Lampung",
        "code": "LA"
      },
      {
        "name": "Maluku",
        "code": "MA"
      },
      {
        "name": "North Maluku",
        "code": "MU"
      },
      {
        "name": "North Sumatra",
        "code": "SU"
      },
      {
        "name": "West Nusa Tenggara",
        "code": "NB"
      },
      {
        "name": "East Nusa Tenggara",
        "code": "NT"
      },
      {
        "name": "Papua",
        "code": "PA"
      },
      {
        "name": "West Papua",
        "code": "PB"
      },
      {
        "name": "Riau",
        "code": "RI"
      },
      {
        "name": "South Sumatra",
        "code": "SS"
      },
      {
        "name": "West Sulawesi",
        "code": "SR"
      },
      {
        "name": "South Sulawesi",
        "code": "SN"
      },
      {
        "name": "Central Sulawesi",
        "code": "ST"
      },
      {
        "name": "Southeast Sulawesi",
        "code": "SG"
      },
      {
        "name": "North Sulawesi",
        "code": "SA"
      },
      {
        "name": "West Sumatra",
        "code": "SB"
      },
      {
        "name": "Yogyakarta",
        "code": "YO"
      }
    ]
  },
  "Vietnam": {
    "code": "VN",
    "phonePrefix": 84,
    "rows": [
      [
        "address1"
      ],
      [
        "address2"
      ],
      [
        "city",
        "zip"
      ]
    ],
    "labels": {
      "address1": "Address",
      "address2": "Apartment, suite, etc",
      "barangay": "District",
      "city": "City",
      "province": "Region",
      "zip": "Postal code"
    },
    "zones": []
  },
  "China": {
    "code": "CN",
    "phonePrefix": 86,
    "rows": [
      [
        "address1"
      ],
      [
        "address2"
      ],
      [
        "city",
        "province",
        "zip"
      ]
    ],
    "labels": {
      "address1": "Full address",
      "address2": "Apartment, suite, etc",
      "barangay": null,
      "city": "City",
      "province": "Province",
      "zip": "Postal code"
    },
    "zones": [
      {
        "name": "Anhui",
        "code": "AH"
      },
      {
        "name": "Beijing",
        "code": "BJ"
      },
      {
        "name": "Chongqing",
        "code": "CQ"
      },
      {
        "name": "Fujian",
        "code": "FJ"
      },
      {
        "name": "Gansu",
        "code": "GS"
      },
      {
        "name": "Guangdong",
        "code": "GD"
      },
      {
        "name": "Guangxi",
        "code": "GX"
      },
      {
        "name": "Guizhou",
        "code": "GZ"
      },
      {
        "name": "Hainan",
        "code": "HI"
      },
      {
        "name": "Hebei",
        "code": "HE"
      },
      {
        "name": "Heilongjiang",
        "code": "HL"
      },
      {
        "name": "Henan",
        "code": "HA"
      },
      {
        "name": "Hubei",
        "code": "HB"
      },
      {
        "name": "Hunan",
        "code": "HN"
      },
      {
        "name": "Inner Mongolia",
        "code": "NM"
      },
      {
        "name": "Jiangsu",
        "code": "JS"
      },
      {
        "name": "Jiangxi",
        "code": "JX"
      },
      {
        "name": "Jilin",
        "code": "JL"
      },
      {
        "name": "Liaoning",
        "code": "LN"
      },
      {
        "name": "Ningxia",
        "code": "NX"
      },
      {
        "name": "Qinghai",
        "code": "QH"
      },
      {
        "name": "Shaanxi",
        "code": "SN"
      },
      {
        "name": "Shandong",
        "code": "SD"
      },
      {
        "name": "Shanghai",
        "code": "SH"
      },
      {
        "name": "Shanxi",
        "code": "SX"
      },
      {
        "name": "Sichuan",
        "code": "SC"
      },
      {
        "name": "Tianjin",
        "code": "TJ"
      },
      {
        "name": "Xinjiang",
        "code": "XJ"
      },
      {
        "name": "Tibet",
        "code": "YZ"
      },
      {
        "name": "Yunnan",
        "code": "YN"
      },
      {
        "name": "Zhejiang",
        "code": "ZJ"
      }
    ]
  }
};
